DROP TABLE users;
DROP TABLE orders;
CREATE TABLE users (id INT, age INT, name TEXT, email TEXT, score INT, PRIMARY KEY(id));
CREATE TABLE orders (order_id INT, user_id INT, amount INT, status TEXT, PRIMARY KEY(order_id));
INSERT INTO users (id, age, name, email, score) VALUES (1,20,'Alice','alice@example.com',85);
INSERT INTO users (id, age, name, email, score) VALUES (2,22,'Bob','bob@example.com',92);
INSERT INTO users (id, age, name, email, score) VALUES (3,19,'Carol','carol@example.com',78);
INSERT INTO users (id, age, name, email, score) VALUES (4,23,'Dave','dave@example.com',88);
INSERT INTO users (id, age, name, email, score) VALUES (5,21,'Eve','eve@example.com',91);
INSERT INTO orders (order_id, user_id, amount, status) VALUES (101,1,250,'PAID');
INSERT INTO orders (order_id, user_id, amount, status) VALUES (102,2,150,'PENDING');
INSERT INTO orders (order_id, user_id, amount, status) VALUES (103,3,75,'PAID');
INSERT INTO orders (order_id, user_id, amount, status) VALUES (104,2,200,'CANCELLED');
INSERT INTO orders (order_id, user_id, amount, status) VALUES (105,5,300,'PAID');
SELECT * FROM users;
SELECT * FROM orders;
SELECT * FROM users WHERE id = 4;
SELECT * FROM orders WHERE order_id = 103;
SELECT * FROM users WHERE score > 90;
SELECT * FROM orders WHERE status = 'PAID';
UPDATE users SET score = 95 WHERE id = 1;
UPDATE orders SET status = 'SHIPPED' WHERE order_id = 105;
SELECT * FROM users WHERE id = 1;
SELECT * FROM orders WHERE order_id = 105;
DELETE FROM users WHERE id = 3;
DELETE FROM orders WHERE status = 'PENDING';
SELECT * FROM users;
SELECT * FROM orders;
DROP TABLE orders;
DROP TABLE users;
exit
